### PR TITLE
added dutch (nl)

### PR DESCRIPTION
**Pull request by TheIndra55**
So how can i get the translator badge 😛

### CODE REVIEW

**Comment by Shadowandsonic** [comment]
poktfy;,,hp[kuh

**Comment by Shadowandsonic** [comment]
add sonic and shadow badges

**Comment by Fabricio20** [comment]
Hey @TheIndra55, sorry for the wait (didn't get mentioned about this PR). If you are still interested in the badge, I need your Discord ID or Username + Discrim.

**Comment by TheIndra55** [comment]
TheIndra#0001 or 241225897389064192

**Pull request merged**
